-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Scmp.Object.Club exposing (..)

import API.CustomCodecs
import API.Scmp.InputObject
import API.Scmp.Interface
import API.Scmp.Object
import API.Scmp.Scalar
import API.Scmp.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet (Maybe API.CustomCodecs.Id) API.Scmp.Object.Club
id =
    Object.selectionForField "(Maybe API.CustomCodecs.Id)" "id" [] (API.CustomCodecs.codecs |> API.Scmp.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


name : SelectionSet (Maybe String) API.Scmp.Object.Club
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


users :
    SelectionSet decodesTo API.Scmp.Object.User
    -> SelectionSet (Maybe (List (Maybe decodesTo))) API.Scmp.Object.Club
users object____ =
    Object.selectionForCompositeField "users" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)
