-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Scmp.Mutation exposing (..)

import API.CustomCodecs
import API.Scmp.InputObject
import API.Scmp.Interface
import API.Scmp.Object
import API.Scmp.Scalar
import API.Scmp.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias AddUserToClubRequiredArguments =
    { clubId : API.CustomCodecs.Id
    , userId : API.CustomCodecs.Id
    }


{-| Add user to Club
-}
addUserToClub :
    AddUserToClubRequiredArguments
    -> SelectionSet decodesTo API.Scmp.Object.AddUserToClubResponse
    -> SelectionSet (Maybe decodesTo) RootMutation
addUserToClub requiredArgs____ object____ =
    Object.selectionForCompositeField "addUserToClub" [ Argument.required "clubId" requiredArgs____.clubId (API.CustomCodecs.codecs |> API.Scmp.Scalar.unwrapEncoder .codecId), Argument.required "userId" requiredArgs____.userId (API.CustomCodecs.codecs |> API.Scmp.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias CreateClubRequiredArguments =
    { name : String }


{-| Create Club
-}
createClub :
    CreateClubRequiredArguments
    -> SelectionSet decodesTo API.Scmp.Object.Club
    -> SelectionSet (Maybe decodesTo) RootMutation
createClub requiredArgs____ object____ =
    Object.selectionForCompositeField "createClub" [ Argument.required "name" requiredArgs____.name Encode.string ] object____ (Basics.identity >> Decode.nullable)


type alias CreateUserRequiredArguments =
    { name : String }


{-| Create User
-}
createUser :
    CreateUserRequiredArguments
    -> SelectionSet decodesTo API.Scmp.Object.User
    -> SelectionSet (Maybe decodesTo) RootMutation
createUser requiredArgs____ object____ =
    Object.selectionForCompositeField "createUser" [ Argument.required "name" requiredArgs____.name Encode.string ] object____ (Basics.identity >> Decode.nullable)


type alias DeleteUserFromClubRequiredArguments =
    { clubId : API.CustomCodecs.Id
    , userId : API.CustomCodecs.Id
    }


{-| Delete user from Club
-}
deleteUserFromClub :
    DeleteUserFromClubRequiredArguments
    -> SelectionSet decodesTo API.Scmp.Object.DeleteUserFromClubResponse
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteUserFromClub requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteUserFromClub" [ Argument.required "clubId" requiredArgs____.clubId (API.CustomCodecs.codecs |> API.Scmp.Scalar.unwrapEncoder .codecId), Argument.required "userId" requiredArgs____.userId (API.CustomCodecs.codecs |> API.Scmp.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)
