-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Scmp.Object exposing (..)


type AddUserToClubResponse
    = AddUserToClubResponse


type Club
    = Club


type DeleteUserFromClubResponse
    = DeleteUserFromClubResponse


type User
    = User
