-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module API.Scmp.ScalarCodecs exposing (..)

import API.Scmp.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    API.Scmp.Scalar.Id


type alias NaiveDateTime =
    API.Scmp.Scalar.NaiveDateTime


codecs : API.Scmp.Scalar.Codecs Id NaiveDateTime
codecs =
    API.Scmp.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecNaiveDateTime = defaultCodecs.codecNaiveDateTime
        }
